version: "3.9"

services:
  backend:
    build: ./ticket-backend
    container_name: ticket-backend
    volumes:
      - ./ticket-backend:/var/www
      - backend_vendor:/var/www/vendor
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./ticket-frontend
    container_name: ticket-frontend
    volumes:
      - ./ticket-frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend


  db:
    image: postgres:15
    container_name: ticket-db
    environment:
      POSTGRES_DB: ticket
      POSTGRES_USER: ticket
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
  frontend_node_modules:
  backend_vendor:
