version: "3.9"

services:
  backend:
    build:
      context: ./ticket-backend
      dockerfile: Dockerfile.prod
    container_name: ticket-backend-prod
    volumes:
      - backend_vendor:/var/www/vendor
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - db
      - redis

  frontend:
    build: ./ticket-frontend
    container_name: ticket-frontend-prod
    volumes:
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
    command: sh -c "npm run build && npm start"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: ticket-db-prod
    environment:
      POSTGRES_DB: ticketing
      POSTGRES_USER: ticket
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data


  redis:
    image: redis:7
    container_name: ticket-redis
    ports:
      - "6379:6379"

volumes:
  dbdata:
  frontend_node_modules:
  backend_vendor:
